export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCESS = "PRODUCT_LIST_SUCESS"
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCESS = "PRODUCT_DETAILS_SUCESS"
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE"

export const ADD_TO_CART ="ADD_TO_CART";
export const REQUEST_FAIL = "REQUEST_FAIL"

export const ADD_To_FAV = "ADD_To_FAV"
export const ERROR_In_ADDING ="ERROR_In_ADDING"