 const ProductData = {
    products: [
        {
            id: "1",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote9pro.jpg",
            modelName: "Redmi Note 9 pro",
            category: "Mobile-Cover",
            price: "₹199",
            countInstock:10,
        },
        {
            id: "2",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote9.jpg",
            modelName: "Redmi Note 9",
            category: "Mobile-Cover",
            price: "₹159",
            countInstock:7,        },
        {
            id: "3",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote8.jpg",
            modelName: "Redmi Note 8",
            category: "Mobile-Cover",
            price: "₹299",
            countInstock:49,
        },
        {
            id: "4",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote8pro.jpg",
            modelName: "Redmi Note 8 pro",
            category: "Mobile-Cover",
            price: "₹209",
            countInstock:66,
        },
        {
            id: "5",
            brandName:"Redmi",
            imagePath: "/backCoverImages/XiaomiMiA2.jpg ",
            modelName: "Xiaomi Mi A2",
            category: "Mobile-Cover",
            price: "₹259",
            countInstock:0,        },
        {
            id: "6",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote7.jpg ",
            modelName: "Redmi Note 7",
            category: "Mobile-Cover",
            price: "₹199",
            countInstock:20,
        },
        {
            id: "7",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote7s.jpg ",
            modelName: "Redmi Note 7s",
            category: "Mobile-Cover",
            price: "₹179",
            countInstock:70,
        },
        {
            id: "8",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote7pro.jpg",
            modelName: "Redmi Note 7 pro",
            category: "Mobile-Cover",
            price: "₹179",
            countInstock:0,        },
        {
            id: "9",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiMiA1.jpg",
            modelName: "Redmi Mi A1",
            category: "Mobile-Cover",
            price: "₹199",
            countInstock:10,
        },
        {
            id: "10",
            brandName:"Redmi",
            imagePath: "/backCoverImages/Redmik20.jpg",
            modelName: "Xiaomi Redmi K20 ",
            category: "Mobile-Cover",
            price: "₹269",
            countInstock:40,
        },
        {
            id: "11",
            brandName:"Redmi",
            imagePath: "/backCoverImages/Redminote6pro.jpg",
            modelName: "Redmi Note 6 pro",
            category: "Mobile-Cover",
            price: "₹199",
            countInstock:0,        },
        {
            id: "12",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiK20pro.jpg",
            modelName: "Redmi K20 pro",
            category: "Mobile-Cover",
            price: "₹299",
            countInstock:10,
        },
        {
            id: "13",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiNote5.jpg ",
            modelName: "Redmi note 5",
            category: "Mobile-Cover",
            price: "₹149",
            countInstock:10,
        },
        {
            id: "14",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiY3.jpg ",
            modelName: " Xiaomi Redmi Y3",
            category: "Mobile-Cover",
            price: "₹199",
            countInstock:20,
        },
        {
            id: "15",
            brandName:"Redmi",
            imagePath: "/backCoverImages/RedmiY2.jpg ",
            modelName: "Xiaomi Redmi Y2",
            category: "Mobile-Cover",
            price: "₹149",
            countInstock:10,
        },
        {
            id: "16",
            brandName:"Realme",
            imagePath: "/backCoverImages/Realme3pro.jpg",
            modelName: "Realme 3 pro",
            category: "Mobile-Cover",
            price: "₹399",
            countInstock:55,
        }, 
        {
            id: "17",
            brandName:"Realme",
            imagePath: "/backCoverImages/RealmeX2.jpg",
            modelName: "Realme 3 pro",
            category: "Mobile-Cover",
            price: "₹399",
            countInstock:0,        }, 
    ],
}

export default ProductData;